apiVersion: v1
kind: ConfigMap
metadata:
  name: chess-config
data:
  DATABASE_URL: "postgres://postgres:postgres@postgres-service:5432/postgres?sslmode=disable"
  REDIS_ADDR: "redis-service:6379"
  FRONTEND_URL: "http://your-domain.com"
  VITE_WS_URL: "ws://api.your-domain.com"
