apiVersion: v1
kind: Secret
metadata:
  name: chess-secret
type: Opaque
data:
  JWT_SECRET: # Replace with base64 of JWT secret
  DB_PASSWORD: # postgres
  GOOGLE_CLIENT_ID: # Replace with base64 of Google Client ID
  GOOGLE_CLIENT_SECRET: # Replace with base64 of Google Client Secret
  GOOGLE_REDIRECT_URI: # Replace with base64 of redirect URI
